<?php
/**
 * Invoice
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Booking Manager API
 *
 * # Booking Manager API for Agencies and Charter Fleets  Booking Manager API is a standard Web service that enables clients to connect their data with external systems and services and to extend the automation benefits of the Booking Manager System. - It is used by charter agencies to publish availabilities of Charter Operators and automate booking processes by connecting Booking Manager to their own web sites to allow for seamless online booking experience for end users or integrating it with their CRM solutions in order to automate office procedures. - Charter operators use the web service to connect Booking Manager with their book keeping softwares and save time and effort in accounting department. - Third Party Software tools also use Booking Manager API to display richer information, for example boat tracking systems are able to visualise client contact information directly on the map showing the boat location in real time. ## Document Changes ### 29.05.2020 - `/companies` more information added in response - address, additional telephone and additional mobile number - `/offers` added `kind` parameter in the request - `/yachts` added `validForBases from/to` parameter to the response ### 10.04.2020   - `/yachts` added `shipyardId` parameter to the response - POST `/addDocument` - function to add document on specific item - `/offers` added `sailingAreaId` as additional parameter in request - PUT `/reservation` added `expirationDate` for options      ### 12.03.2020. - Extras valid for certain yacht in `/yachts` - `/yachts` function with extras duration parameter - `validDaysFrom`/`validDaysTo` - `/yachts` function with year of build `year`, default yacht deposit `deposit`, commision percentage `commissionPercentage` and default check in day `defaultCheckInDay` - `/yacht` field `lenghtAtWaterline` corrected to length
 *
 * The version of the OpenAPI document: 2.0.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Invoice model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class Invoice 
{
        /**
     * @var int|null
     * @SerializedName("type")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $type = null;

    /**
     * @var string|null
     * @SerializedName("invoiceCode")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $invoiceCode = null;

    /**
     * @var string|null
     * @SerializedName("reservationNumber")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $reservationNumber = null;

    /**
     * @var Datetime|null
     * @SerializedName("invoiceDate")
     * @Assert\Type("OpenAPI\Server\Model\Datetime")
     * @Type("OpenAPI\Server\Model\Datetime")
     */
    protected ?Datetime $invoiceDate = null;

    /**
     * @var string|null
     * @SerializedName("client")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $client = null;

    /**
     * @var string|null
     * @SerializedName("clientCode")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $clientCode = null;

    /**
     * @var string|null
     * @SerializedName("clientVatCode")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $clientVatCode = null;

    /**
     * @var int|null
     * @SerializedName("clientId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $clientId = null;

    /**
     * @var string|null
     * @SerializedName("guestName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $guestName = null;

    /**
     * @var string|null
     * @SerializedName("currency")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $currency = null;

    /**
     * @var 
     * @SerializedName("exchangeRate")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected  $exchangeRate = null;

    /**
     * @var string|null
     * @SerializedName("altCurrency")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $altCurrency = null;

    /**
     * @var 
     * @SerializedName("altExchangeRate")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected  $altExchangeRate = null;

    /**
     * @var string|null
     * @SerializedName("resource")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $resource = null;

    /**
     * @var string|null
     * @SerializedName("resourceType")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $resourceType = null;

    /**
     * @var int|null
     * @SerializedName("resourceCode")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $resourceCode = null;

    /**
     * @var 
     * @SerializedName("totalPrice")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected  $totalPrice = null;

    /**
     * @var 
     * @SerializedName("totalPriceWithoutTax")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected  $totalPriceWithoutTax = null;

    /**
     * @var 
     * @SerializedName("rate")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected  $rate = null;

    /**
     * @var 
     * @SerializedName("totalAltPrice")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected  $totalAltPrice = null;

    /**
     * @var 
     * @SerializedName("totalAltPriceWithoutTax")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected  $totalAltPriceWithoutTax = null;

    /**
     * @var string|null
     * @SerializedName("baseFrom")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $baseFrom = null;

    /**
     * @var string|null
     * @SerializedName("baseTo")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $baseTo = null;

    /**
     * @var bool|null
     * @SerializedName("alreadyTransferred")
     * @Assert\Type("bool")
     * @Type("bool")
     */
    protected ?bool $alreadyTransferred = null;

    /**
     * @var Datetime|null
     * @SerializedName("serviceDateFrom")
     * @Assert\Type("OpenAPI\Server\Model\Datetime")
     * @Type("OpenAPI\Server\Model\Datetime")
     */
    protected ?Datetime $serviceDateFrom = null;

    /**
     * @var Datetime|null
     * @SerializedName("serviceDateTo")
     * @Assert\Type("OpenAPI\Server\Model\Datetime")
     * @Type("OpenAPI\Server\Model\Datetime")
     */
    protected ?Datetime $serviceDateTo = null;

    /**
     * @var string|null
     * @SerializedName("paymentMethodName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $paymentMethodName = null;

    /**
     * @var string|null
     * @SerializedName("paymentMethodType")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $paymentMethodType = null;

    /**
     * @var int|null
     * @SerializedName("agencyId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $agencyId = null;

    /**
     * @var string|null
     * @SerializedName("agencyName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $agencyName = null;

    /**
     * @var string|null
     * @SerializedName("agencyCode")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $agencyCode = null;

    /**
     * @var string|null
     * @SerializedName("agencyVatCode")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $agencyVatCode = null;

    /**
     * @var int|null
     * @SerializedName("relatedReservationId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $relatedReservationId = null;

    /**
     * @var int|null
     * @SerializedName("reservationId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $reservationId = null;

    /**
     * @var string|null
     * @SerializedName("relatedInvoiceNumber")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $relatedInvoiceNumber = null;

    /**
     * @var array|null
     * @SerializedName("vat")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\Vat")
     * })
     * @Type("array<OpenAPI\Server\Model\Vat>")
     */
    protected ?array $vat = null;

    /**
     * @var array|null
     * @SerializedName("services")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\Services")
     * })
     * @Type("array<OpenAPI\Server\Model\Services>")
     */
    protected ?array $services = null;

    /**
     * @var array|null
     * @SerializedName("bi")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\Bi")
     * })
     * @Type("array<OpenAPI\Server\Model\Bi>")
     */
    protected ?array $bi = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->type = $data['type'] ?? null;
        $this->invoiceCode = $data['invoiceCode'] ?? null;
        $this->reservationNumber = $data['reservationNumber'] ?? null;
        $this->invoiceDate = $data['invoiceDate'] ?? null;
        $this->client = $data['client'] ?? null;
        $this->clientCode = $data['clientCode'] ?? null;
        $this->clientVatCode = $data['clientVatCode'] ?? null;
        $this->clientId = $data['clientId'] ?? null;
        $this->guestName = $data['guestName'] ?? null;
        $this->currency = $data['currency'] ?? null;
        $this->exchangeRate = $data['exchangeRate'] ?? null;
        $this->altCurrency = $data['altCurrency'] ?? null;
        $this->altExchangeRate = $data['altExchangeRate'] ?? null;
        $this->resource = $data['resource'] ?? null;
        $this->resourceType = $data['resourceType'] ?? null;
        $this->resourceCode = $data['resourceCode'] ?? null;
        $this->totalPrice = $data['totalPrice'] ?? null;
        $this->totalPriceWithoutTax = $data['totalPriceWithoutTax'] ?? null;
        $this->rate = $data['rate'] ?? null;
        $this->totalAltPrice = $data['totalAltPrice'] ?? null;
        $this->totalAltPriceWithoutTax = $data['totalAltPriceWithoutTax'] ?? null;
        $this->baseFrom = $data['baseFrom'] ?? null;
        $this->baseTo = $data['baseTo'] ?? null;
        $this->alreadyTransferred = $data['alreadyTransferred'] ?? null;
        $this->serviceDateFrom = $data['serviceDateFrom'] ?? null;
        $this->serviceDateTo = $data['serviceDateTo'] ?? null;
        $this->paymentMethodName = $data['paymentMethodName'] ?? null;
        $this->paymentMethodType = $data['paymentMethodType'] ?? null;
        $this->agencyId = $data['agencyId'] ?? null;
        $this->agencyName = $data['agencyName'] ?? null;
        $this->agencyCode = $data['agencyCode'] ?? null;
        $this->agencyVatCode = $data['agencyVatCode'] ?? null;
        $this->relatedReservationId = $data['relatedReservationId'] ?? null;
        $this->reservationId = $data['reservationId'] ?? null;
        $this->relatedInvoiceNumber = $data['relatedInvoiceNumber'] ?? null;
        $this->vat = $data['vat'] ?? null;
        $this->services = $data['services'] ?? null;
        $this->bi = $data['bi'] ?? null;
    }

    /**
     * Gets type.
     *
     * @return int|null
     */
    public function getType(): ?int
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param int|null $type
     *
     * @return $this
     */
    public function setType(?int $type = null): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets invoiceCode.
     *
     * @return string|null
     */
    public function getInvoiceCode(): ?string
    {
        return $this->invoiceCode;
    }

    /**
     * Sets invoiceCode.
     *
     * @param string|null $invoiceCode
     *
     * @return $this
     */
    public function setInvoiceCode(?string $invoiceCode = null): self
    {
        $this->invoiceCode = $invoiceCode;

        return $this;
    }

    /**
     * Gets reservationNumber.
     *
     * @return string|null
     */
    public function getReservationNumber(): ?string
    {
        return $this->reservationNumber;
    }

    /**
     * Sets reservationNumber.
     *
     * @param string|null $reservationNumber
     *
     * @return $this
     */
    public function setReservationNumber(?string $reservationNumber = null): self
    {
        $this->reservationNumber = $reservationNumber;

        return $this;
    }

    /**
     * Gets invoiceDate.
     *
     * @return Datetime|null
     */
    public function getInvoiceDate(): ?Datetime
    {
        return $this->invoiceDate;
    }

    /**
     * Sets invoiceDate.
     *
     * @param Datetime|null $invoiceDate
     *
     * @return $this
     */
    public function setInvoiceDate(?Datetime $invoiceDate = null): self
    {
        $this->invoiceDate = $invoiceDate;

        return $this;
    }

    /**
     * Gets client.
     *
     * @return string|null
     */
    public function getClient(): ?string
    {
        return $this->client;
    }

    /**
     * Sets client.
     *
     * @param string|null $client
     *
     * @return $this
     */
    public function setClient(?string $client = null): self
    {
        $this->client = $client;

        return $this;
    }

    /**
     * Gets clientCode.
     *
     * @return string|null
     */
    public function getClientCode(): ?string
    {
        return $this->clientCode;
    }

    /**
     * Sets clientCode.
     *
     * @param string|null $clientCode
     *
     * @return $this
     */
    public function setClientCode(?string $clientCode = null): self
    {
        $this->clientCode = $clientCode;

        return $this;
    }

    /**
     * Gets clientVatCode.
     *
     * @return string|null
     */
    public function getClientVatCode(): ?string
    {
        return $this->clientVatCode;
    }

    /**
     * Sets clientVatCode.
     *
     * @param string|null $clientVatCode
     *
     * @return $this
     */
    public function setClientVatCode(?string $clientVatCode = null): self
    {
        $this->clientVatCode = $clientVatCode;

        return $this;
    }

    /**
     * Gets clientId.
     *
     * @return int|null
     */
    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    /**
     * Sets clientId.
     *
     * @param int|null $clientId
     *
     * @return $this
     */
    public function setClientId(?int $clientId = null): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    /**
     * Gets guestName.
     *
     * @return string|null
     */
    public function getGuestName(): ?string
    {
        return $this->guestName;
    }

    /**
     * Sets guestName.
     *
     * @param string|null $guestName
     *
     * @return $this
     */
    public function setGuestName(?string $guestName = null): self
    {
        $this->guestName = $guestName;

        return $this;
    }

    /**
     * Gets currency.
     *
     * @return string|null
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets currency.
     *
     * @param string|null $currency
     *
     * @return $this
     */
    public function setCurrency(?string $currency = null): self
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * Gets exchangeRate.
     *
     * @return 
     */
    public function getExchangeRate(): 
    {
        return $this->exchangeRate;
    }

    /**
     * Sets exchangeRate.
     *
     * @param  $exchangeRate
     *
     * @return $this
     */
    public function setExchangeRate( $exchangeRate = null): self
    {
        $this->exchangeRate = $exchangeRate;

        return $this;
    }

    /**
     * Gets altCurrency.
     *
     * @return string|null
     */
    public function getAltCurrency(): ?string
    {
        return $this->altCurrency;
    }

    /**
     * Sets altCurrency.
     *
     * @param string|null $altCurrency
     *
     * @return $this
     */
    public function setAltCurrency(?string $altCurrency = null): self
    {
        $this->altCurrency = $altCurrency;

        return $this;
    }

    /**
     * Gets altExchangeRate.
     *
     * @return 
     */
    public function getAltExchangeRate(): 
    {
        return $this->altExchangeRate;
    }

    /**
     * Sets altExchangeRate.
     *
     * @param  $altExchangeRate
     *
     * @return $this
     */
    public function setAltExchangeRate( $altExchangeRate = null): self
    {
        $this->altExchangeRate = $altExchangeRate;

        return $this;
    }

    /**
     * Gets resource.
     *
     * @return string|null
     */
    public function getResource(): ?string
    {
        return $this->resource;
    }

    /**
     * Sets resource.
     *
     * @param string|null $resource
     *
     * @return $this
     */
    public function setResource(?string $resource = null): self
    {
        $this->resource = $resource;

        return $this;
    }

    /**
     * Gets resourceType.
     *
     * @return string|null
     */
    public function getResourceType(): ?string
    {
        return $this->resourceType;
    }

    /**
     * Sets resourceType.
     *
     * @param string|null $resourceType
     *
     * @return $this
     */
    public function setResourceType(?string $resourceType = null): self
    {
        $this->resourceType = $resourceType;

        return $this;
    }

    /**
     * Gets resourceCode.
     *
     * @return int|null
     */
    public function getResourceCode(): ?int
    {
        return $this->resourceCode;
    }

    /**
     * Sets resourceCode.
     *
     * @param int|null $resourceCode
     *
     * @return $this
     */
    public function setResourceCode(?int $resourceCode = null): self
    {
        $this->resourceCode = $resourceCode;

        return $this;
    }

    /**
     * Gets totalPrice.
     *
     * @return 
     */
    public function getTotalPrice(): 
    {
        return $this->totalPrice;
    }

    /**
     * Sets totalPrice.
     *
     * @param  $totalPrice
     *
     * @return $this
     */
    public function setTotalPrice( $totalPrice = null): self
    {
        $this->totalPrice = $totalPrice;

        return $this;
    }

    /**
     * Gets totalPriceWithoutTax.
     *
     * @return 
     */
    public function getTotalPriceWithoutTax(): 
    {
        return $this->totalPriceWithoutTax;
    }

    /**
     * Sets totalPriceWithoutTax.
     *
     * @param  $totalPriceWithoutTax
     *
     * @return $this
     */
    public function setTotalPriceWithoutTax( $totalPriceWithoutTax = null): self
    {
        $this->totalPriceWithoutTax = $totalPriceWithoutTax;

        return $this;
    }

    /**
     * Gets rate.
     *
     * @return 
     */
    public function getRate(): 
    {
        return $this->rate;
    }

    /**
     * Sets rate.
     *
     * @param  $rate
     *
     * @return $this
     */
    public function setRate( $rate = null): self
    {
        $this->rate = $rate;

        return $this;
    }

    /**
     * Gets totalAltPrice.
     *
     * @return 
     */
    public function getTotalAltPrice(): 
    {
        return $this->totalAltPrice;
    }

    /**
     * Sets totalAltPrice.
     *
     * @param  $totalAltPrice
     *
     * @return $this
     */
    public function setTotalAltPrice( $totalAltPrice = null): self
    {
        $this->totalAltPrice = $totalAltPrice;

        return $this;
    }

    /**
     * Gets totalAltPriceWithoutTax.
     *
     * @return 
     */
    public function getTotalAltPriceWithoutTax(): 
    {
        return $this->totalAltPriceWithoutTax;
    }

    /**
     * Sets totalAltPriceWithoutTax.
     *
     * @param  $totalAltPriceWithoutTax
     *
     * @return $this
     */
    public function setTotalAltPriceWithoutTax( $totalAltPriceWithoutTax = null): self
    {
        $this->totalAltPriceWithoutTax = $totalAltPriceWithoutTax;

        return $this;
    }

    /**
     * Gets baseFrom.
     *
     * @return string|null
     */
    public function getBaseFrom(): ?string
    {
        return $this->baseFrom;
    }

    /**
     * Sets baseFrom.
     *
     * @param string|null $baseFrom
     *
     * @return $this
     */
    public function setBaseFrom(?string $baseFrom = null): self
    {
        $this->baseFrom = $baseFrom;

        return $this;
    }

    /**
     * Gets baseTo.
     *
     * @return string|null
     */
    public function getBaseTo(): ?string
    {
        return $this->baseTo;
    }

    /**
     * Sets baseTo.
     *
     * @param string|null $baseTo
     *
     * @return $this
     */
    public function setBaseTo(?string $baseTo = null): self
    {
        $this->baseTo = $baseTo;

        return $this;
    }

    /**
     * Gets alreadyTransferred.
     *
     * @return bool|null
     */
    public function isAlreadyTransferred(): ?bool
    {
        return $this->alreadyTransferred;
    }

    /**
     * Sets alreadyTransferred.
     *
     * @param bool|null $alreadyTransferred
     *
     * @return $this
     */
    public function setAlreadyTransferred(?bool $alreadyTransferred = null): self
    {
        $this->alreadyTransferred = $alreadyTransferred;

        return $this;
    }

    /**
     * Gets serviceDateFrom.
     *
     * @return Datetime|null
     */
    public function getServiceDateFrom(): ?Datetime
    {
        return $this->serviceDateFrom;
    }

    /**
     * Sets serviceDateFrom.
     *
     * @param Datetime|null $serviceDateFrom
     *
     * @return $this
     */
    public function setServiceDateFrom(?Datetime $serviceDateFrom = null): self
    {
        $this->serviceDateFrom = $serviceDateFrom;

        return $this;
    }

    /**
     * Gets serviceDateTo.
     *
     * @return Datetime|null
     */
    public function getServiceDateTo(): ?Datetime
    {
        return $this->serviceDateTo;
    }

    /**
     * Sets serviceDateTo.
     *
     * @param Datetime|null $serviceDateTo
     *
     * @return $this
     */
    public function setServiceDateTo(?Datetime $serviceDateTo = null): self
    {
        $this->serviceDateTo = $serviceDateTo;

        return $this;
    }

    /**
     * Gets paymentMethodName.
     *
     * @return string|null
     */
    public function getPaymentMethodName(): ?string
    {
        return $this->paymentMethodName;
    }

    /**
     * Sets paymentMethodName.
     *
     * @param string|null $paymentMethodName
     *
     * @return $this
     */
    public function setPaymentMethodName(?string $paymentMethodName = null): self
    {
        $this->paymentMethodName = $paymentMethodName;

        return $this;
    }

    /**
     * Gets paymentMethodType.
     *
     * @return string|null
     */
    public function getPaymentMethodType(): ?string
    {
        return $this->paymentMethodType;
    }

    /**
     * Sets paymentMethodType.
     *
     * @param string|null $paymentMethodType
     *
     * @return $this
     */
    public function setPaymentMethodType(?string $paymentMethodType = null): self
    {
        $this->paymentMethodType = $paymentMethodType;

        return $this;
    }

    /**
     * Gets agencyId.
     *
     * @return int|null
     */
    public function getAgencyId(): ?int
    {
        return $this->agencyId;
    }

    /**
     * Sets agencyId.
     *
     * @param int|null $agencyId
     *
     * @return $this
     */
    public function setAgencyId(?int $agencyId = null): self
    {
        $this->agencyId = $agencyId;

        return $this;
    }

    /**
     * Gets agencyName.
     *
     * @return string|null
     */
    public function getAgencyName(): ?string
    {
        return $this->agencyName;
    }

    /**
     * Sets agencyName.
     *
     * @param string|null $agencyName
     *
     * @return $this
     */
    public function setAgencyName(?string $agencyName = null): self
    {
        $this->agencyName = $agencyName;

        return $this;
    }

    /**
     * Gets agencyCode.
     *
     * @return string|null
     */
    public function getAgencyCode(): ?string
    {
        return $this->agencyCode;
    }

    /**
     * Sets agencyCode.
     *
     * @param string|null $agencyCode
     *
     * @return $this
     */
    public function setAgencyCode(?string $agencyCode = null): self
    {
        $this->agencyCode = $agencyCode;

        return $this;
    }

    /**
     * Gets agencyVatCode.
     *
     * @return string|null
     */
    public function getAgencyVatCode(): ?string
    {
        return $this->agencyVatCode;
    }

    /**
     * Sets agencyVatCode.
     *
     * @param string|null $agencyVatCode
     *
     * @return $this
     */
    public function setAgencyVatCode(?string $agencyVatCode = null): self
    {
        $this->agencyVatCode = $agencyVatCode;

        return $this;
    }

    /**
     * Gets relatedReservationId.
     *
     * @return int|null
     */
    public function getRelatedReservationId(): ?int
    {
        return $this->relatedReservationId;
    }

    /**
     * Sets relatedReservationId.
     *
     * @param int|null $relatedReservationId
     *
     * @return $this
     */
    public function setRelatedReservationId(?int $relatedReservationId = null): self
    {
        $this->relatedReservationId = $relatedReservationId;

        return $this;
    }

    /**
     * Gets reservationId.
     *
     * @return int|null
     */
    public function getReservationId(): ?int
    {
        return $this->reservationId;
    }

    /**
     * Sets reservationId.
     *
     * @param int|null $reservationId
     *
     * @return $this
     */
    public function setReservationId(?int $reservationId = null): self
    {
        $this->reservationId = $reservationId;

        return $this;
    }

    /**
     * Gets relatedInvoiceNumber.
     *
     * @return string|null
     */
    public function getRelatedInvoiceNumber(): ?string
    {
        return $this->relatedInvoiceNumber;
    }

    /**
     * Sets relatedInvoiceNumber.
     *
     * @param string|null $relatedInvoiceNumber
     *
     * @return $this
     */
    public function setRelatedInvoiceNumber(?string $relatedInvoiceNumber = null): self
    {
        $this->relatedInvoiceNumber = $relatedInvoiceNumber;

        return $this;
    }

    /**
     * Gets vat.
     *
     * @return array|null
     */
    public function getVat(): ?array
    {
        return $this->vat;
    }

    /**
     * Sets vat.
     *
     * @param array|null $vat
     *
     * @return $this
     */
    public function setVat(?array $vat = null): self
    {
        $this->vat = $vat;

        return $this;
    }

    /**
     * Gets services.
     *
     * @return array|null
     */
    public function getServices(): ?array
    {
        return $this->services;
    }

    /**
     * Sets services.
     *
     * @param array|null $services
     *
     * @return $this
     */
    public function setServices(?array $services = null): self
    {
        $this->services = $services;

        return $this;
    }

    /**
     * Gets bi.
     *
     * @return array|null
     */
    public function getBi(): ?array
    {
        return $this->bi;
    }

    /**
     * Sets bi.
     *
     * @param array|null $bi
     *
     * @return $this
     */
    public function setBi(?array $bi = null): self
    {
        $this->bi = $bi;

        return $this;
    }
}


