<?php
/**
 * Price
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Booking Manager API
 *
 * # Booking Manager API for Agencies and Charter Fleets  Booking Manager API is a standard Web service that enables clients to connect their data with external systems and services and to extend the automation benefits of the Booking Manager System. - It is used by charter agencies to publish availabilities of Charter Operators and automate booking processes by connecting Booking Manager to their own web sites to allow for seamless online booking experience for end users or integrating it with their CRM solutions in order to automate office procedures. - Charter operators use the web service to connect Booking Manager with their book keeping softwares and save time and effort in accounting department. - Third Party Software tools also use Booking Manager API to display richer information, for example boat tracking systems are able to visualise client contact information directly on the map showing the boat location in real time. ## Document Changes ### 29.05.2020 - `/companies` more information added in response - address, additional telephone and additional mobile number - `/offers` added `kind` parameter in the request - `/yachts` added `validForBases from/to` parameter to the response ### 10.04.2020   - `/yachts` added `shipyardId` parameter to the response - POST `/addDocument` - function to add document on specific item - `/offers` added `sailingAreaId` as additional parameter in request - PUT `/reservation` added `expirationDate` for options      ### 12.03.2020. - Extras valid for certain yacht in `/yachts` - `/yachts` function with extras duration parameter - `validDaysFrom`/`validDaysTo` - `/yachts` function with year of build `year`, default yacht deposit `deposit`, commision percentage `commissionPercentage` and default check in day `defaultCheckInDay` - `/yacht` field `lenghtAtWaterline` corrected to length
 *
 * The version of the OpenAPI document: 2.0.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Price model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class Price 
{
        /**
     * @var int|null
     * @SerializedName("yachtId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $yachtId = null;

    /**
     * @var Datetime|null
     * @SerializedName("dateFrom")
     * @Assert\Type("OpenAPI\Server\Model\Datetime")
     * @Type("OpenAPI\Server\Model\Datetime")
     */
    protected ?Datetime $dateFrom = null;

    /**
     * @var Datetime|null
     * @SerializedName("dateTo")
     * @Assert\Type("OpenAPI\Server\Model\Datetime")
     * @Type("OpenAPI\Server\Model\Datetime")
     */
    protected ?Datetime $dateTo = null;

    /**
     * @var string|null
     * @SerializedName("product")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $product = null;

    /**
     * @var 
     * @SerializedName("price")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected  $price = null;

    /**
     * @var string|null
     * @SerializedName("currency")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $currency = null;

    /**
     * @var 
     * @SerializedName("startPrice")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected  $startPrice = null;

    /**
     * @var float|null
     * @SerializedName("discountPercentage")
     * @Assert\Type("float")
     * @Type("float")
     */
    protected ?float $discountPercentage = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->yachtId = $data['yachtId'] ?? null;
        $this->dateFrom = $data['dateFrom'] ?? null;
        $this->dateTo = $data['dateTo'] ?? null;
        $this->product = $data['product'] ?? null;
        $this->price = $data['price'] ?? null;
        $this->currency = $data['currency'] ?? null;
        $this->startPrice = $data['startPrice'] ?? null;
        $this->discountPercentage = $data['discountPercentage'] ?? null;
    }

    /**
     * Gets yachtId.
     *
     * @return int|null
     */
    public function getYachtId(): ?int
    {
        return $this->yachtId;
    }

    /**
     * Sets yachtId.
     *
     * @param int|null $yachtId
     *
     * @return $this
     */
    public function setYachtId(?int $yachtId = null): self
    {
        $this->yachtId = $yachtId;

        return $this;
    }

    /**
     * Gets dateFrom.
     *
     * @return Datetime|null
     */
    public function getDateFrom(): ?Datetime
    {
        return $this->dateFrom;
    }

    /**
     * Sets dateFrom.
     *
     * @param Datetime|null $dateFrom
     *
     * @return $this
     */
    public function setDateFrom(?Datetime $dateFrom = null): self
    {
        $this->dateFrom = $dateFrom;

        return $this;
    }

    /**
     * Gets dateTo.
     *
     * @return Datetime|null
     */
    public function getDateTo(): ?Datetime
    {
        return $this->dateTo;
    }

    /**
     * Sets dateTo.
     *
     * @param Datetime|null $dateTo
     *
     * @return $this
     */
    public function setDateTo(?Datetime $dateTo = null): self
    {
        $this->dateTo = $dateTo;

        return $this;
    }

    /**
     * Gets product.
     *
     * @return string|null
     */
    public function getProduct(): ?string
    {
        return $this->product;
    }

    /**
     * Sets product.
     *
     * @param string|null $product
     *
     * @return $this
     */
    public function setProduct(?string $product = null): self
    {
        $this->product = $product;

        return $this;
    }

    /**
     * Gets price.
     *
     * @return 
     */
    public function getPrice(): 
    {
        return $this->price;
    }

    /**
     * Sets price.
     *
     * @param  $price
     *
     * @return $this
     */
    public function setPrice( $price = null): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Gets currency.
     *
     * @return string|null
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets currency.
     *
     * @param string|null $currency
     *
     * @return $this
     */
    public function setCurrency(?string $currency = null): self
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * Gets startPrice.
     *
     * @return 
     */
    public function getStartPrice(): 
    {
        return $this->startPrice;
    }

    /**
     * Sets startPrice.
     *
     * @param  $startPrice
     *
     * @return $this
     */
    public function setStartPrice( $startPrice = null): self
    {
        $this->startPrice = $startPrice;

        return $this;
    }

    /**
     * Gets discountPercentage.
     *
     * @return float|null
     */
    public function getDiscountPercentage(): ?float
    {
        return $this->discountPercentage;
    }

    /**
     * Sets discountPercentage.
     *
     * @param float|null $discountPercentage
     *
     * @return $this
     */
    public function setDiscountPercentage(?float $discountPercentage = null): self
    {
        $this->discountPercentage = $discountPercentage;

        return $this;
    }
}


