<?php
/**
 * Reservation
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Booking Manager API
 *
 * # Booking Manager API for Agencies and Charter Fleets  Booking Manager API is a standard Web service that enables clients to connect their data with external systems and services and to extend the automation benefits of the Booking Manager System. - It is used by charter agencies to publish availabilities of Charter Operators and automate booking processes by connecting Booking Manager to their own web sites to allow for seamless online booking experience for end users or integrating it with their CRM solutions in order to automate office procedures. - Charter operators use the web service to connect Booking Manager with their book keeping softwares and save time and effort in accounting department. - Third Party Software tools also use Booking Manager API to display richer information, for example boat tracking systems are able to visualise client contact information directly on the map showing the boat location in real time. ## Document Changes ### 29.05.2020 - `/companies` more information added in response - address, additional telephone and additional mobile number - `/offers` added `kind` parameter in the request - `/yachts` added `validForBases from/to` parameter to the response ### 10.04.2020   - `/yachts` added `shipyardId` parameter to the response - POST `/addDocument` - function to add document on specific item - `/offers` added `sailingAreaId` as additional parameter in request - PUT `/reservation` added `expirationDate` for options      ### 12.03.2020. - Extras valid for certain yacht in `/yachts` - `/yachts` function with extras duration parameter - `validDaysFrom`/`validDaysTo` - `/yachts` function with year of build `year`, default yacht deposit `deposit`, commision percentage `commissionPercentage` and default check in day `defaultCheckInDay` - `/yacht` field `lenghtAtWaterline` corrected to length
 *
 * The version of the OpenAPI document: 2.0.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Reservation model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class Reservation 
{
        /**
     * @var \DateTime|null
     * @SerializedName("dateFrom")
     * @Assert\NotNull()
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected ?\DateTime $dateFrom = null;

    /**
     * @var \DateTime|null
     * @SerializedName("dateTo")
     * @Assert\NotNull()
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected ?\DateTime $dateTo = null;

    /**
     * @var int|null
     * @SerializedName("yachtId")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $yachtId = null;

    /**
     * @var int|null
     * @SerializedName("status")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $status = null;

    /**
     * @var string|null
     * @SerializedName("productName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $productName = null;

    /**
     * @var int|null
     * @SerializedName("baseFromId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $baseFromId = null;

    /**
     * @var int|null
     * @SerializedName("baseToId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $baseToId = null;

    /**
     * @var string|null
     * @SerializedName("clientName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $clientName = null;

    /**
     * @var int|null
     * @SerializedName("cliendId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $cliendId = null;

    /**
     * @var string|null
     * @SerializedName("currency")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $currency = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->dateFrom = $data['dateFrom'] ?? null;
        $this->dateTo = $data['dateTo'] ?? null;
        $this->yachtId = $data['yachtId'] ?? null;
        $this->status = $data['status'] ?? null;
        $this->productName = $data['productName'] ?? null;
        $this->baseFromId = $data['baseFromId'] ?? null;
        $this->baseToId = $data['baseToId'] ?? null;
        $this->clientName = $data['clientName'] ?? null;
        $this->cliendId = $data['cliendId'] ?? null;
        $this->currency = $data['currency'] ?? null;
    }

    /**
     * Gets dateFrom.
     *
     * @return \DateTime|null
     */
    public function getDateFrom(): ?\DateTime
    {
        return $this->dateFrom;
    }

    /**
     * Sets dateFrom.
     *
     * @param \DateTime|null $dateFrom
     *
     * @return $this
     */
    public function setDateFrom(?\DateTime $dateFrom): self
    {
        $this->dateFrom = $dateFrom;

        return $this;
    }

    /**
     * Gets dateTo.
     *
     * @return \DateTime|null
     */
    public function getDateTo(): ?\DateTime
    {
        return $this->dateTo;
    }

    /**
     * Sets dateTo.
     *
     * @param \DateTime|null $dateTo
     *
     * @return $this
     */
    public function setDateTo(?\DateTime $dateTo): self
    {
        $this->dateTo = $dateTo;

        return $this;
    }

    /**
     * Gets yachtId.
     *
     * @return int|null
     */
    public function getYachtId(): ?int
    {
        return $this->yachtId;
    }

    /**
     * Sets yachtId.
     *
     * @param int|null $yachtId
     *
     * @return $this
     */
    public function setYachtId(?int $yachtId): self
    {
        $this->yachtId = $yachtId;

        return $this;
    }

    /**
     * Gets status.
     *
     * @return int|null
     */
    public function getStatus(): ?int
    {
        return $this->status;
    }

    /**
     * Sets status.
     *
     * @param int|null $status
     *
     * @return $this
     */
    public function setStatus(?int $status = null): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Gets productName.
     *
     * @return string|null
     */
    public function getProductName(): ?string
    {
        return $this->productName;
    }

    /**
     * Sets productName.
     *
     * @param string|null $productName
     *
     * @return $this
     */
    public function setProductName(?string $productName = null): self
    {
        $this->productName = $productName;

        return $this;
    }

    /**
     * Gets baseFromId.
     *
     * @return int|null
     */
    public function getBaseFromId(): ?int
    {
        return $this->baseFromId;
    }

    /**
     * Sets baseFromId.
     *
     * @param int|null $baseFromId
     *
     * @return $this
     */
    public function setBaseFromId(?int $baseFromId = null): self
    {
        $this->baseFromId = $baseFromId;

        return $this;
    }

    /**
     * Gets baseToId.
     *
     * @return int|null
     */
    public function getBaseToId(): ?int
    {
        return $this->baseToId;
    }

    /**
     * Sets baseToId.
     *
     * @param int|null $baseToId
     *
     * @return $this
     */
    public function setBaseToId(?int $baseToId = null): self
    {
        $this->baseToId = $baseToId;

        return $this;
    }

    /**
     * Gets clientName.
     *
     * @return string|null
     */
    public function getClientName(): ?string
    {
        return $this->clientName;
    }

    /**
     * Sets clientName.
     *
     * @param string|null $clientName
     *
     * @return $this
     */
    public function setClientName(?string $clientName = null): self
    {
        $this->clientName = $clientName;

        return $this;
    }

    /**
     * Gets cliendId.
     *
     * @return int|null
     */
    public function getCliendId(): ?int
    {
        return $this->cliendId;
    }

    /**
     * Sets cliendId.
     *
     * @param int|null $cliendId
     *
     * @return $this
     */
    public function setCliendId(?int $cliendId = null): self
    {
        $this->cliendId = $cliendId;

        return $this;
    }

    /**
     * Gets currency.
     *
     * @return string|null
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets currency.
     *
     * @param string|null $currency
     *
     * @return $this
     */
    public function setCurrency(?string $currency = null): self
    {
        $this->currency = $currency;

        return $this;
    }
}


